# Site settings
title: University Log
email: edward_prince@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am keeping this as a sort of online log/diary of my events at uni. 
  Hopefully ranging from lectures to nights out, to my thoughts and opinions
  on other topics.
baseurl: "/uni-log/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  edprince

# Build settings
markdown: kramdown
